# This scenario deploys a cluster with
# 3 core members and 1 read replica.
acceptLicenseAgreement: "yes"
neo4jPassword: "mySecretPassword"

core:
    standalone: false
    numberOfServers: 3

readReplica:
    numberOfServers: 1

podAnnotations:
    sidecar.istio.io/inject: "false"
    my-custom-annotation: 24

podLabels:
    example: "label"
    second: "example"
