apiVersion: v1
appVersion: 4.1.3
description: Neo4j is the world's leading graph database
home: https://www.neo4j.com
icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
keywords:
- graph
- database
- cypher
maintainers:
- email: david.allen@neo4j.com
  name: moxious
- email: bledi.feshti@neo4j.com
  name: bfeshti
- email: mark.needham@neo4j.com
  name: mneedham
name: neo4j
sources:
- https://github.com/neo4j/neo4j
- https://github.com/neo4j/docker-neo4j
- https://github.com/neo4j-contrib/neo4j-helm
version: 4.1.3-1
