# permissions for end users to view netpolwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netpolwatcher-viewer-role
rules:
- apiGroups:
  - netpol.qaware.com
  resources:
  - netpolwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netpol.qaware.com
  resources:
  - netpolwatchers/status
  verbs:
  - get
