# This ConfigMap gets passed to all core cluster members to configure them.
# Take note that some networking settings like internal hostname still get configured
# when the pod starts, but most non-networking specific configs can be tailored here.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "neo4j.coreConfig.fullname" . }}
data:
  NEO4J_dbms_directories_logs: "{{ .Values.core.persistentVolume.mountPath }}/logs"
  {{- if .Values.core.standalone }}
  # https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_dbms.mode
  NEO4J_dbms_mode: SINGLE
  {{- else }}
  NEO4J_dbms_mode: CORE
  {{- end }}
