apiVersion: v1
kind: ConfigMap
metadata:
  name: "standalone-fabric-config"
data:
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_fabric_database_name: fabric
  NEO4J_fabric_routing_servers: fabric-example-neo4j-core-0.fabric-example-neo4j.default.svc.cluster.local:7687
